import { planHomeMigration } from "../src/codex-home-migration";
import { identity } from "../launcher/electron/web-home.cjs";
import { loadConfig } from "../src/config";
import { installCodexIntegration, inspectCodexIntegration } from "../src/codex-integration";
const plan = planHomeMigration();
if (process.argv[2] && (!plan || identity(process.argv[2]) !== identity(plan.nativeHome))) throw new Error("Requested native home does not match a pending migration; use isolation ensure after migration");
installCodexIntegration(loadConfig());
const status = inspectCodexIntegration();
if (status.errors.length) throw new Error(status.errors.join("; "));
console.log(JSON.stringify({ active: status.active, configPath: status.configPath, codexRestartRequired: true }));
